name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Repository
      run: git clone https://activitypub.software/TransFem-org/Sharkey.git

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Read version from package.json
      id: version
      run: echo "VERSION=$(jq -r '.version' Sharkey/package.json)" >> $GITHUB_ENV

    - name: Copy docker-compose file
      run: cp Sharkey/compose_example.yml Sharkey/docker-compose.yml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: juneink
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image
      working-directory: ./Sharkey
      run: |
        docker buildx build --platform linux/amd64 --build-arg VERSION=${{ env.VERSION }} -t juneink/sharkey:${{ env.VERSION }} -t juneink/sharkey:latest --push .
