name: CI

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 手动触发

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Clone Repository
      run: git clone https://activitypub.software/TransFem-org/Sharkey.git

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get Docker Latest Tag
      id: docker_latest
      run: |
        repository="juneink/sharkey"
        response=$(curl -s "https://hub.docker.com/v2/repositories/$repository/tags/")
        latest_info=$(echo "$response" | jq -r '.results[] | select(.name=="latest")')
        if [ -z "$latest_info" ]; then
          echo "未找到 'latest' 标签"
          exit 1
        fi
        latest_digest=$(echo "$latest_info" | jq -r '.digest')
        matching_tags=$(echo "$response" | jq -r --arg digest "$latest_digest" '.results[] | select(.digest==$digest) | .name')
        echo "::set-output name=latest_version::$matching_tags"

    - name: Read version from package.json
      id: version
      run: echo "dev_version=$(jq -r '.version' Sharkey/package.json)" >> $GITHUB_ENV

    - name: Compare Versions
      id: compare
      run: echo "latest_version=${{ steps.docker_latest.outputs.latest_version }}" >> $GITHUB_ENV

    - name: Copy docker-compose file
      run: cp Sharkey/compose_example.yml Sharkey/docker-compose.yml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: juneink
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image
      if: env.latest_version != env.dev_version
      working-directory: ./Sharkey
      run: |
        echo "Docker镜像版本过旧，开始构建..."
        docker buildx build --platform linux/amd64 --build-arg VERSION=${{ env.dev_version }} -t juneink/sharkey:${{ env.dev_version }} -t juneink/sharkey:latest --push .
