name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Repository
      run: git clone https://activitypub.software/TransFem-org/Sharkey.git

    - name: Install jq
      run: sudo apt-get install jq

    - name: Read version from package.json
      id: version
      run: echo "VERSION=$(jq -r '.version' Sharkey/package.json)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      working-directory: ./Sharkey
      run: docker compose build --build-arg VERSION=${{ env.VERSION }}
