name: Version Compare

on:
  workflow_dispatch:

jobs:
  compare-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Clone Remote Repository
      run: git clone https://activitypub.software/TransFem-org/Sharkey.git

    - name: Get Version from Remote package.json
      id: remote_version
      run: echo "remote_version=$(jq -r '.version' Sharkey/package.json)" >> $GITHUB_ENV

    - name: Get Docker Latest Digest
      id: docker_digest
      run: |
        repository="juneink/sharkey"
        response=$(curl -s "https://hub.docker.com/v2/repositories/$repository/tags/")
        latest_info=$(echo "$response" | jq -r '.results[] | select(.name=="latest")')
        digest=$(echo "$latest_info" | jq -r '.images[0].digest')
        echo "latest_digest=$digest" >> $GITHUB_ENV

    - name: Get Version from Docker Latest Digest
      id: docker_version
      run: |
        repository="juneink/sharkey"
        response=$(curl -s "https://hub.docker.com/v2/repositories/$repository/tags/")
        latest_tag=$(echo "$response" | jq -r --arg digest "$digest" '.results[] | select(.images[0].digest==$digest) | .name')
        echo "docker_version=$latest_tag" >> $GITHUB_ENV

    - name: Compare Versions
      run: |
        echo "Remote package.json version: ${{ env.remote_version }}"
        echo "Docker latest version: ${{ env.docker_version }}"
        if [ "${{ env.remote_version }}" != "${{ env.docker_version }}" ]; then
          echo "版本不同，本地 version 文件已更新为远程版本。"
        else
          echo "本地 version 文件与远程版本一致，无需更新。"
        fi
