name: Version Compare

on:
  workflow_dispatch:

jobs:
  compare-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      # 从GitHub仓库中检出代码
      # 输出: 检出成功，无输出

    - name: Install jq
      run: sudo apt-get install -y jq
      # 安装jq工具用于JSON解析
      # 预期输出: jq安装成功的信息

    - name: Clone Remote Repository
      run: git clone https://activitypub.software/TransFem-org/Sharkey.git
      # 克隆远程仓库以获取package.json
      # 预期输出: Cloning into 'Sharkey'...

    - name: Get Version from Remote package.json
      id: remote_version
      run: echo "remote_version=$(jq -r '.version' Sharkey/package.json)" >> $GITHUB_ENV
      # 从远程仓库的package.json中获取版本号
      # 预期输出: 无直接输出，版本号被存储到环境变量

    - name: Get Docker Latest Digest
      id: docker_digest
      run: |
        repository="juneink/sharkey"
        response=$(curl -s "https://hub.docker.com/v2/repositories/$repository/tags/")
        latest_info=$(echo "$response" | jq -r '.results[] | select(.name=="latest")')
        digest=$(echo "$latest_info" | jq -r '.images[0].digest')
        echo "latest_digest=$digest" >> $GITHUB_ENV
      # 获取Docker Hub上latest标签的digest
      # 预期输出: 无直接输出，digest被存储到环境变量

    - name: Get Version from Docker Latest Digest
      id: docker_version
      run: |
        repository="juneink/sharkey"
        response=$(curl -s "https://hub.docker.com/v2/repositories/$repository/tags/")
        latest_tag=$(echo "$response" | jq -r --arg digest "$digest" '.results[] | select(.images[0].digest==$digest) | .name')
        echo "docker_version=$latest_tag" >> $GITHUB_ENV
      # 从Docker Hub获取latest版本的标签名作为版本号
      # 预期输出: 无直接输出，版本号被存储到环境变量

    - name: Compare Versions
      run: |
        echo "Remote package.json version: ${{ env.remote_version }}"
        echo "Docker latest version: ${{ env.docker_version }}"
        if [ "${{ env.remote_version }}" != "${{ env.docker_version }}" ]; then
          echo "版本不同，本地 version 文件已更新为远程版本。"
        else
          echo "本地 version 文件与远程版本一致，无需更新。"
        fi
      # 比较远程版本和Docker版本，并输出比较结果
      # 预期输出: 版本不同或版本一致的相应消息
